import { IconData } from '@iconiq/shared';

// This file is auto-generated by the build script
// It will be populated during the build process

// Define empty exports that will be populated during build
export const Icons: Record<string, IconData> = {};
